// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeVt3zuAjpt0fgEiWoV27FkiEd6qZWM_I',
    appId: '1:822602561257:web:25486a1269f20854256278',
    messagingSenderId: '822602561257',
    projectId: 'bai-tap-lon-3be05',
    authDomain: 'bai-tap-lon-3be05.firebaseapp.com',
    storageBucket: 'bai-tap-lon-3be05.appspot.com',
    measurementId: 'G-YM8THE6EVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkwrvEH56P2JEuiAFe9r2iUwViZY4K_wc',
    appId: '1:822602561257:android:1f1466af77d1d4a9256278',
    messagingSenderId: '822602561257',
    projectId: 'bai-tap-lon-3be05',
    storageBucket: 'bai-tap-lon-3be05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBijyAIjhXrLwVtZpvx5pi3m34ieDy60PM',
    appId: '1:822602561257:ios:a4d4c3106eabafb5256278',
    messagingSenderId: '822602561257',
    projectId: 'bai-tap-lon-3be05',
    storageBucket: 'bai-tap-lon-3be05.appspot.com',
    iosBundleId: 'com.example.baiTapDiema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBijyAIjhXrLwVtZpvx5pi3m34ieDy60PM',
    appId: '1:822602561257:ios:a4d4c3106eabafb5256278',
    messagingSenderId: '822602561257',
    projectId: 'bai-tap-lon-3be05',
    storageBucket: 'bai-tap-lon-3be05.appspot.com',
    iosBundleId: 'com.example.baiTapDiema',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeVt3zuAjpt0fgEiWoV27FkiEd6qZWM_I',
    appId: '1:822602561257:web:5ca265cb907f260a256278',
    messagingSenderId: '822602561257',
    projectId: 'bai-tap-lon-3be05',
    authDomain: 'bai-tap-lon-3be05.firebaseapp.com',
    storageBucket: 'bai-tap-lon-3be05.appspot.com',
    measurementId: 'G-P2RFS1SWBL',
  );
}
